// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djshqfpwjpvxzvfiohvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqc2hxZnB3anB2eHp2ZmlvaHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDA3MzYsImV4cCI6MjA2NDI3NjczNn0.ra0Jm1UC7sxdWZDDEVNtFjl1BA31VYj0vOXGitDbcjU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);